name: BanFromShops
main: com.github.blarosen95.BFC.Main
version: 1.1.0
author: The_Dale_Gribble
description: Ban players from your ChestShop shops and, if they are within one of your claims, warps them to spawn.
depend: [GriefPrevention, ChestShop]
api-version: 1.13
commands:
  banfromshops:
    usage: /<command> <Target Player>
    aliases: [bfs]
  bfsreload:
    usage: /<command>
  unbanfromshops:
    usage: /<command> <Target Player>
    aliases: [ubfs]
  shopbans:
    usage: /<command>
permissions:
  banfromshops.ban:
    default: true
  banfromshops.ban.exempt:
    default: op
  banfromshops.reload:
    default: op