name: BanFromClaim
main: com.github.blarosen95.BFC.Main
version: 1.1.0
author: The_Dale_Gribble
description: Ban players from your current Grief Prevention Claim.
softdepend: [GriefPrevention, ChestShop]
api-version: 1.13
commands:
  banfromclaim:
    usage: /<command> <Target Player>
    aliases: [bfc]
  bfcreload:
    usage: /<command>
  unbanfromclaim:
    usage: /<command> <Target Player>
    aliases: [ubfc]
  claimbans:
    usage: /<command>
permissions:
  banfromclaim.ban:
    default: true
  banfromclaim.ban.exempt:
    default: op
  banfromclaim.reload:
    default: op