name: BanFromShops
main: com.github.blarosen95.BFC.Main
version: 2.0.2
author: The_Dale_Gribble
description: Ban players from your ChestShop shops and, if they are within one of your claims, warps them to spawn.
depend: [GriefPrevention, ChestShop]
api-version: 1.13
commands:
  shopban:
    usage: /<command> <Target Player>
  bfsreload:
    usage: /<command>
  shopunban:
    usage: /<command> <Target Player>
  shopbans:
    usage: /<command>
permissions:
  banfromshops.ban:
    default: true
  banfromshops.ban.exempt:
    default: op
  banfromshops.reload:
    default: op