Messages:
  PlayersOnly: "&cOnly in-game players can use /{COMMAND}"
  NoPermission: "&cYou do not have permission to use /{COMMAND}"
  BanFromClaimUsage: "/{COMMAND} <Target Player> - Ban a player from your shops."
  SettingsReloaded: "&aBFC Settings reloaded!"
  CantBanSelf: "&cYou cannot ban yourself!"
  PlayerOffline: "&cNo one with &4{ARGUMENT} &cin their name is Online!"
  NotInClaim: "&cYou're not in a claim"
  NotManager: "&cYou're not a manager of that claim!"
  Exempt: "{PLAYER} cannot be banned from shops!"
  CantBanTrusted: "&cYou cannot ban players with AccessTrust or higher!"
  NoSafeLocation: "&c{PLAYER} was not banned because no safe location was found!"
  BanSuccessful: "&a{PLAYER} was banned from your shops!"
  BanSuccessfulWithWarp: "&a{PLAYER} was banned from your shops and was teleported out of one of your claims!"
  NoClaimBans: "&6You do not currently have any players banned from your shops."
  OneClaimBan: "&6You currently have 1 player banned from your shops:\n&c{LIST}"
  MultipleClaimBans: "&6You currently have {COUNT} players banned from your shops:\n&c{LIST}"
  CantShopHere: "&c{PLAYER} has banned you from their shops, you'll have to shop elsewhere."
  NoSuchPlayer: "&c{PLAYER} does not exist."
  UnbanFromClaimUsage: "/{COMMAND} <Target Player> - Unban a player from your shops."